name: variables and secrets

env:
  WF_VAR: "Workflow level variable"

on:
  push:

jobs:
  test_variables:
    env:
      JOB_VAR: "Job lvl variable"
    name: job to test vars
    runs-on: ubuntu-latest
    steps:
      - name: test vars
        id: stepVar
        env: 
          STE_VAR: "Step lvl variable"
        run: |
          echo ${{ github.actor }}
          echo $GITHUB_JOB
          echo $WF_VAR
          echo $JOB_VAR
          echo $STEP_VAR
          echo ${{ vars.CONF_VAR }}
          echo ${{ secrets.A_SECRET }}
