name: workflow overview

on:
  workflow_dispatch:
  
jobs:
  a_simple_job:
    name: my simple job name
    runs-on: ubuntu-latest
    steps:
      - name: name of my step
        id: stepId
        run: echo "this is the 1st step fromt he 1st job"
        
      - name: step with anohter shell
        id: shellStep
        shell: python
        run: print("this is using python shell")
