name: workflow overview

on:
  workflow_dispatch:
  push:
    branches:
      - main
  
jobs:
  my_self_hosted_job:
    name: my self hosted job
    runs-on: self-hosted
    steps: 
      - name: step in a self-hosted runner
        id: selfHOstedId
        shell: cmd
        run: | 
          echo this is a multiline comment
          echo and this job has been executed for my self-hosted runner
          
  a_simple_job:
    name: my simple job name
    runs-on: ubuntu-latest
    steps:
      - name: name of my step
        id: stepId
        run: echo "this is the 1st step fromt he 1st job"
        
      - name: step with anohter shell
        id: shellStep
        shell: python
        run: print("this is using python shell")
